[tool.ruff]

# Extend root configuration. Note that having this [tool.ruff] section in a pyproject in examples
# has the effect of making each example package treated as first-party, where `dagster` and
# integrations will be treated as third-party. This is appropriate for example code.
extend = "../pyproject.toml"
