version: 2

sources:
  - name: jaffle_shop
    schema: "{% if target.name == 'dev' %}main{% else %}{{ target.schema }}{% endif %}"
    tables:
      - name: raw_customers
        meta:
          dagster:
            asset_key: ["raw_source_customers"]
