config: # this should be ignored
  send_anonymous_usage_stats: false
  use_colors: true

jaffle_shop:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DAGSTER_DBT_PYTEST_XDIST_DUCKDB_DBFILE_PATH') }}"
      threads: 24
